src/Entity/Todo.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TodoRepository")
 */
class Todo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $due_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_date;

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDueDate(): ?string
    {
        return $this->due_date;
    }

    public function setDueDate(string $due_date): self
    {
        $this->due_date = $due_date;

        return $this;
    }

    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->create_date;
    }

    public function setCreateDate(\DateTimeInterface $create_date): self
    {
        $this->create_date = $create_date;

        return $this;
    }
}

src/Form/TodoType.php
<?php

namespace App\Form;

use App\Entity\Todo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TodoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('category')
            ->add('description')
            ->add('due_date')
            ->add('create_date')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Todo::class,
        ]);
    }
}

src/Controller/TodoController.php
<?php

namespace App\Controller;

use App\Entity\Todo;
use App\Form\TodoType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class TodoController extends Controller
{
    /**
     * @Route("/", name="todo")
     */
    public function index()
    {
        $todos = $this->getDoctrine()
            ->getRepository(Todo::class)
            ->findAll();

        dump($todos);

        return $this->render('todo/index.html.twig', [
            'controller_name' => 'TodoController',
            'todos' => $todos
        ]);
    }

    /**
     * @Route("/view/{id}", name="todo_view")
     * @param $id
     */
    public function view($id)
    {
        $todo = $this->getDoctrine()
            ->getRepository(Todo::class)
            ->find($id);

        dump($todo);

        return $this->render('todo/view.html.twig', [
            'todo' => $todo
        ]);
    }

    /**
     * @Route("/edit/{id}", name="todo_edit")
     */
    public function edit($id, Request $request)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $todo = $entityManager
            ->getRepository(Todo::class)
            ->find($id);

        $form = $this->createForm(TodoType::class, $todo);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            $todo->setName($data->getName());
            $todo->setCategory($data->getCategory());
            $todo->setDescription($data->getDescription());
            $todo->setDueDate($data->getDueDate());
            $todo->setCreateDate($data->getCreateDate());

            $entityManager->persist($todo);
            $entityManager->flush();

            return $this->redirectToRoute('todo_view', [
                'id' => $id
            ]);
        }

        dump($todo);

        return $this->render('todo/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/delete/{id}", name="todo_delete")
     */
    public function delete($id)
    {
        $entityManager = $this->getDoctrine()->getManager();

        $todo = $entityManager
            ->getRepository(Todo::class)
            ->find($id);

        $entityManager->remove($todo);

        $entityManager->flush();

        return $this->redirectToRoute('todo');
    }

    /**
     * @Route("/create", name="todo_create")
     */
    public function create(Request $request)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $form = $this->createForm(TodoType::class);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            $todo = new Todo();
            $todo->setName($data->getName());
            $todo->setCategory($data->getCategory());
            $todo->setDescription($data->getDescription());
            $todo->setDueDate($data->getDueDate());
            $todo->setCreateDate($data->getCreateDate());

            $entityManager->persist($todo);
            $entityManager->flush();

            return $this->redirectToRoute("todo");
        }

        return $this->render('todo/create.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    {% block stylesheets %}{% endblock %}
</head>
<body>
<div class="container">
    {% block body %}{% endblock %}
</div>
{% block javascripts %}{% endblock %}
</body>
</html>

templates/todo/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="panel-default panel">

    <a href="{{ path('todo') }}">Go back</a>

</div>
{{ form_start(form) }}
{{ form_widget(form) }}

<div class="form-group row">
    <div class="col-sm-2"></div>
    <div class="col-sm-10 text-right">
        <input type="submit" value="Safe" class="btn btn-success"/>

    </div>
</div>


{% endblock %}

templates/todo/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="panel-default panel">

    <a href="{{ path('todo') }}">Go back</a>

</div>
    {{ form_start(form) }}
    {{ form_widget(form) }}

<div class="form-group row">
    <div class="col-sm-2"></div>
    <div class="col-sm-10 text-right">
        <input type="submit" value="Safe" class="btn btn-success"/>

    </div>
</div>


    {{ form_end(form) }}
{% endblock %}

templates/todo/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<div class="panel panel-success">
    <div class="panel-heading">
        <a href="{{ path("todo_create") }}">Create</a>
    </div>
</div>

<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Category</th>
        <th scope="col">Due Date</th>
        <th scope="col">Create Date</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for todo in todos %}
    <tr>
        <th scope="row">{{ todo.id }}</th>
        <td>{{ todo.name }}</td>
        <td>{{ todo.description }}</td>
        <td>{{ todo.category }}</td>
        <td>{{ todo.dueDate }}</td>
        <td>{{ todo.createDate | date('d-m-Y') }}</td>
        <td>
            <a href="{{ path('todo_view', {'id': todo.id}) }}" class="btn btn-success">View</a>
            <a href="{{ path('todo_edit', {'id': todo.id}) }}" class="btn btn-info">Edit</a>
            <a href="{{ path('todo_delete', {'id': todo.id}) }}" class="btn btn-danger">Delete</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/todo/view.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="panel-default panel">
    <a href="{{ path('todo') }}">Go back</a>

</div>
<ul class="list-group">
    <li class="list-group-item active">#{{ todo.id }}: {{ todo.name }}</li>
    <li class="list-group-item">{{ todo.category }}</li>
    <li class="list-group-item">{{ todo.description }}</li>
    <li class="list-group-item">{{ todo.dueDate }}</li>
    <li class="list-group-item">{{ todo.createDate| date('d-m-y') }}</li>
</ul>
{% endblock %}